
package com.istudy.server.common.protocol.ws.xxt;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.8
 * 2014-01-16T15:46:31.125+08:00
 * Generated source version: 2.7.8
 * 
 */
public final class Cmcc_CmccSOAP_Client {

    private static final QName SERVICE_NAME = new QName("http://www.cmcc.com/edu/", "cmcc");

    private Cmcc_CmccSOAP_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = Cmcc_Service.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        Cmcc_Service ss = new Cmcc_Service(wsdlURL, SERVICE_NAME);
        Cmcc port = ss.getCmccSOAP();  
        
        {
        System.out.println("Invoking edu...");
        com.istudy.server.common.protocol.ws.xxt.Request _edu_parameters = null;
        com.istudy.server.common.protocol.ws.xxt.Response _edu__return = port.edu(_edu_parameters);
        System.out.println("edu.result=" + _edu__return);


        }

        System.exit(0);
    }

}
