package com.istudy.server.common.protocol.ws.xxt;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.8
 * 2014-01-16T15:46:31.172+08:00
 * Generated source version: 2.7.8
 * 
 */
@WebServiceClient(name = "cmcc", 
                  wsdlLocation = "xxt.wsdl",
                  targetNamespace = "http://www.cmcc.com/edu/") 
public class Cmcc_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.cmcc.com/edu/", "cmcc");
    public final static QName CmccSOAP = new QName("http://www.cmcc.com/edu/", "cmccSOAP");
    static {
        URL url = Cmcc_Service.class.getResource("xxt.wsdl");
        if (url == null) {
            url = Cmcc_Service.class.getClassLoader().getResource("xxt.wsdl");
        } 
        if (url == null) {
            java.util.logging.Logger.getLogger(Cmcc_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "xxt.wsdl");
        }       
        WSDL_LOCATION = url;
    }

    public Cmcc_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public Cmcc_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Cmcc_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public Cmcc_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public Cmcc_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public Cmcc_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns Cmcc
     */
    @WebEndpoint(name = "cmccSOAP")
    public Cmcc getCmccSOAP() {
        return super.getPort(CmccSOAP, Cmcc.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Cmcc
     */
    @WebEndpoint(name = "cmccSOAP")
    public Cmcc getCmccSOAP(WebServiceFeature... features) {
        return super.getPort(CmccSOAP, Cmcc.class, features);
    }

}
